- name: "Install Minecraft"
  hosts: all
  become: true
  vars_files:
    - vars/main.yml
  tasks:
    - name: "Install Minecraft"
      ansible.builtin.include_tasks: tasks/main.yml
  handlers:
    - ansible.builtin.import_tasks: handlers/main.yml 